export interface LeaguePreset {
  key: string;
  label: string;
  country: string;
  tier: string;
  league_home_goals_avg: string;
  league_away_goals_avg: string;
  dixon_coles_rho: string;
  shrinkage_matches: string;
  sourceLabel: string;
  sourceUrl: string;
  sourceNote: string;
}

export const DEFAULT_LEAGUE_KEY = "Liga Portugal";

export const LEAGUE_PRESETS: LeaguePreset[] = [
  {
    key: "Liga Portugal",
    label: "Liga Portugal",
    country: "Portugal",
    tier: "1st division",
    league_home_goals_avg: "1.49",
    league_away_goals_avg: "1.21",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/portugal/liga-portugal/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Liga Portugal 2",
    label: "Liga Portugal 2",
    country: "Portugal",
    tier: "2nd division",
    league_home_goals_avg: "1.26",
    league_away_goals_avg: "1.19",
    dixon_coles_rho: "-0.09",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/portugal/liga-portugal-2/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Liga Revelação Sub23",
    label: "Liga Revelação Sub23",
    country: "Portugal",
    tier: "U23 competition",
    league_home_goals_avg: "1.74",
    league_away_goals_avg: "1.22",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "5",
    sourceLabel: "DollarClown",
    sourceUrl: "https://dollarclown.com/portugal/liga-revelao-u23/goals-scored",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Premier League",
    label: "Premier League",
    country: "England",
    tier: "1st division",
    league_home_goals_avg: "1.50",
    league_away_goals_avg: "1.24",
    dixon_coles_rho: "-0.06",
    shrinkage_matches: "5",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/england/premier-league/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Championship",
    label: "Championship",
    country: "England",
    tier: "2nd division",
    league_home_goals_avg: "1.39",
    league_away_goals_avg: "1.18",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/england/championship/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "League One",
    label: "League One",
    country: "England",
    tier: "3rd division",
    league_home_goals_avg: "1.46",
    league_away_goals_avg: "1.07",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/england/league-one/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Argelia Ligue 1",
    label: "Argelia Ligue 1",
    country: "Algeria",
    tier: "1st division",
    league_home_goals_avg: "1.27",
    league_away_goals_avg: "0.89",
    dixon_coles_rho: "-0.10",
    shrinkage_matches: "8",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/algeria/ligue-1",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Bahraini Premier League",
    label: "Bahraini Premier League",
    country: "Bahrain",
    tier: "1st division",
    league_home_goals_avg: "1.25",
    league_away_goals_avg: "1.12",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "7",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/bahrain/bahraini-premier-league",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Liga Primera",
    label: "Liga Primera",
    country: "Nicaragua",
    tier: "1st division",
    league_home_goals_avg: "1.64",
    league_away_goals_avg: "1.29",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "6",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/nicaragua/primera-division",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Liga Nacional de Futbol de Guatemala",
    label: "Liga Nacional de Futbol de Guatemala",
    country: "Guatemala",
    tier: "1st division",
    league_home_goals_avg: "1.54",
    league_away_goals_avg: "0.81",
    dixon_coles_rho: "-0.10",
    shrinkage_matches: "7",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/guatemala/liga-nacional-de-futbol-de-guatemala",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Primera Categoria Serie A",
    label: "Primera Categoria Serie A",
    country: "Ecuador",
    tier: "1st division",
    league_home_goals_avg: "1.11",
    league_away_goals_avg: "0.86",
    dixon_coles_rho: "-0.11",
    shrinkage_matches: "8",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/ecuador/primera-categoria-serie-a",
    sourceNote: "2026 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "Primera Categoria Serie B",
    label: "Primera Categoria Serie B",
    country: "Ecuador",
    tier: "2nd division",
    league_home_goals_avg: "1.43",
    league_away_goals_avg: "0.82",
    dixon_coles_rho: "-0.10",
    shrinkage_matches: "8",
    sourceLabel: "SoccerStats",
    sourceUrl: "https://www.soccerstats.com/trends.asp?league=ecuador2",
    sourceNote: "2025 season snapshot used because the 2026 secondary-league feed is still incomplete on the primary source.",
  },
  {
    key: "PrvaLiga",
    label: "PrvaLiga",
    country: "Slovenia",
    tier: "1st division",
    league_home_goals_avg: "1.69",
    league_away_goals_avg: "1.42",
    dixon_coles_rho: "-0.04",
    shrinkage_matches: "5",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/slovenia/prvaliga",
    sourceNote: "2025/26 snapshot based on current home and away scoring averages across the competition.",
  },
  {
    key: "La Liga",
    label: "La Liga",
    country: "Spain",
    tier: "1st division",
    league_home_goals_avg: "1.51",
    league_away_goals_avg: "1.11",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/spain/laliga/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "LaLiga2",
    label: "LaLiga2",
    country: "Spain",
    tier: "2nd division",
    league_home_goals_avg: "1.44",
    league_away_goals_avg: "1.17",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/spain/laliga2/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Serie A",
    label: "Serie A",
    country: "Italy",
    tier: "1st division",
    league_home_goals_avg: "1.27",
    league_away_goals_avg: "1.13",
    dixon_coles_rho: "-0.09",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/italy/serie-a/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Serie B",
    label: "Serie B",
    country: "Italy",
    tier: "2nd division",
    league_home_goals_avg: "1.48",
    league_away_goals_avg: "1.08",
    dixon_coles_rho: "-0.09",
    shrinkage_matches: "7",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/italy/serie-b",
    sourceNote: "2025/26 league stats, using the latest snapshot available.",
  },
  {
    key: "Bundesliga",
    label: "Bundesliga",
    country: "Germany",
    tier: "1st division",
    league_home_goals_avg: "1.73",
    league_away_goals_avg: "1.47",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "5",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/germany/bundesliga/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "2. Bundesliga",
    label: "2. Bundesliga",
    country: "Germany",
    tier: "2nd division",
    league_home_goals_avg: "1.49",
    league_away_goals_avg: "1.32",
    dixon_coles_rho: "-0.06",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/germany/2-bundesliga/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Ligue 1",
    label: "Ligue 1",
    country: "France",
    tier: "1st division",
    league_home_goals_avg: "1.59",
    league_away_goals_avg: "1.19",
    dixon_coles_rho: "-0.07",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/france/ligue-1/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Ligue 2",
    label: "Ligue 2",
    country: "France",
    tier: "2nd division",
    league_home_goals_avg: "1.29",
    league_away_goals_avg: "1.19",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/france/ligue-2/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Eredivisie",
    label: "Eredivisie",
    country: "Netherlands",
    tier: "1st division",
    league_home_goals_avg: "1.80",
    league_away_goals_avg: "1.39",
    dixon_coles_rho: "-0.04",
    shrinkage_matches: "5",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/netherlands/eredivisie",
    sourceNote: "2025/26 league stats, using the latest snapshot available.",
  },
  {
    key: "Eerste Divisie",
    label: "Eerste Divisie",
    country: "Netherlands",
    tier: "2nd division",
    league_home_goals_avg: "1.70",
    league_away_goals_avg: "1.50",
    dixon_coles_rho: "-0.03",
    shrinkage_matches: "5",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/netherlands/eerste-divisie/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Super Lig",
    label: "Super Lig",
    country: "Turkey",
    tier: "1st division",
    league_home_goals_avg: "1.31",
    league_away_goals_avg: "1.29",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/turkey/super-lig/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "1. Lig",
    label: "1. Lig",
    country: "Turkey",
    tier: "2nd division",
    league_home_goals_avg: "1.66",
    league_away_goals_avg: "1.21",
    dixon_coles_rho: "-0.07",
    shrinkage_matches: "7",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/turkey/1-lig/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Saudi Pro League",
    label: "Saudi Pro League",
    country: "Saudi Arabia",
    tier: "1st division",
    league_home_goals_avg: "1.56",
    league_away_goals_avg: "1.41",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "5",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/saudi-arabia/saudi-professional-league/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Primera División",
    label: "Primera División",
    country: "Argentina",
    tier: "1st division",
    league_home_goals_avg: "1.18",
    league_away_goals_avg: "0.86",
    dixon_coles_rho: "-0.11",
    shrinkage_matches: "8",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/argentina/primera-division",
    sourceNote: "2026 league stats, using the latest snapshot available.",
  },
  {
    key: "Primera Nacional",
    label: "Primera Nacional",
    country: "Argentina",
    tier: "2nd division",
    league_home_goals_avg: "1.07",
    league_away_goals_avg: "0.80",
    dixon_coles_rho: "-0.12",
    shrinkage_matches: "8",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/argentina/prim-b-nacional",
    sourceNote: "2026 league stats, using the latest snapshot available.",
  },
  {
    key: "Jupiler Pro League",
    label: "Jupiler Pro League",
    country: "Belgium",
    tier: "1st division",
    league_home_goals_avg: "1.36",
    league_away_goals_avg: "1.16",
    dixon_coles_rho: "-0.07",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/belgium/jupiler-pro-league/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Challenger Pro League",
    label: "Challenger Pro League",
    country: "Belgium",
    tier: "2nd division",
    league_home_goals_avg: "1.42",
    league_away_goals_avg: "1.37",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "6",
    sourceLabel: "Betmana",
    sourceUrl: "https://betmana.co.uk/football/leagues/belgium/challenger_pro_league/",
    sourceNote: "2025/26 league stats, used because an equivalent BetExplorer stats page was not surfaced reliably.",
  },
  {
    key: "Bulgaria First League",
    label: "Bulgaria First League",
    country: "Bulgaria",
    tier: "1st division",
    league_home_goals_avg: "1.27",
    league_away_goals_avg: "1.08",
    dixon_coles_rho: "-0.09",
    shrinkage_matches: "7",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/bulgaria/first-league",
    sourceNote: "2025/26 league stats, using the latest snapshot available.",
  },
  {
    key: "Greece Super League",
    label: "Greece Super League",
    country: "Greece",
    tier: "1st division",
    league_home_goals_avg: "1.39",
    league_away_goals_avg: "1.11",
    dixon_coles_rho: "-0.09",
    shrinkage_matches: "6",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/greece/super-league",
    sourceNote: "2025/26 league stats, using the latest snapshot available.",
  },
  {
    key: "Switzerland Super League",
    label: "Switzerland Super League",
    country: "Switzerland",
    tier: "1st division",
    league_home_goals_avg: "1.80",
    league_away_goals_avg: "1.47",
    dixon_coles_rho: "-0.04",
    shrinkage_matches: "5",
    sourceLabel: "FootyStats",
    sourceUrl: "https://footystats.org/switzerland/super-league",
    sourceNote: "2025/26 league stats, using the latest snapshot available.",
  },
  {
    key: "HNL",
    label: "HNL",
    country: "Croatia",
    tier: "1st division",
    league_home_goals_avg: "1.50",
    league_away_goals_avg: "1.21",
    dixon_coles_rho: "-0.08",
    shrinkage_matches: "6",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/croatia/hnl/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
  {
    key: "Denmark Superliga",
    label: "Denmark Superliga",
    country: "Denmark",
    tier: "1st division",
    league_home_goals_avg: "1.74",
    league_away_goals_avg: "1.48",
    dixon_coles_rho: "-0.05",
    shrinkage_matches: "5",
    sourceLabel: "BetExplorer",
    sourceUrl: "https://www.betexplorer.com/football/denmark/superliga/stats/",
    sourceNote: "2025/26 league stats, updated for the current season snapshot.",
  },
];

export const LEAGUE_PRESET_MAP = Object.fromEntries(
  LEAGUE_PRESETS.map((preset) => [preset.key, preset])
) as Record<string, LeaguePreset>;
