/**
 * The "Plano Milhão" as written: €10 turned into a million across 38 days,
 * one bet a day, each day's winnings staked again.
 *
 * The document's day-by-day table is not a list of arbitrary numbers, it is
 * generated by the rules beside it: a percentage of the bankroll that steps
 * down as the stake grows, at odds that cycle through a fixed set. Rebuilding
 * it from those rules rather than transcribing 38 rows means the ladder and
 * the rules can never drift apart, and the ladder still lands on the same
 * figures the brothers wrote down (day 38 ends just over €1,007,000).
 *
 * The plan is now one challenge among several, so the machinery lives in
 * challengeRules.ts and this file is the document's own settings fed into it.
 * Everything here is the same plan it always was, read through the general
 * engine instead of hard-coded a second time.
 */

import {
  MILLION_PLAN_RULES,
  buildLadder as buildLadderFor,
  chanceOfCompleting as chanceOfCompletingFor,
  checkBet as checkBetAgainst,
  costOfOneLoss as costOfOneLossFor,
  plannedOddsForDay as plannedOddsFor,
  plannedStake as plannedStakeFor,
  rungForBankroll as rungForBankrollIn,
  stakePctForDay as stakePctFor,
  type BetCheckInput,
  type Rung,
  type Violation,
  type ViolationSeverity,
} from "@/lib/challengeRules";
import { planSchedule as schedule } from "@/lib/challengeSchedule";

export { MILLION_PLAN_RULES };
export type { BetCheckInput, ViolationSeverity };
export type PlanRung = Rung;
export type PlanViolation = Violation;

export const PLAN_START = 10;
export const PLAN_TARGET = 1_000_000;
export const PLAN_DAYS = MILLION_PLAN_RULES.days;

/** The document's safe range for a single bet. */
export const ODDS_MIN = MILLION_PLAN_RULES.oddsMin!;
export const ODDS_MAX = MILLION_PLAN_RULES.oddsMax!;

/** Losses in a row after which the plan says to stop for the day. */
export const LOSS_STREAK_PAUSE = MILLION_PLAN_RULES.lossStreakPause!;

/**
 * What share of the bankroll the plan stakes on a given day.
 *
 * The written section of the document lists a different set of bands
 * (50/40/30/20) than its own table, and those bands do not reach a million —
 * they end around €14,000. These are the table's, which is the ladder the plan
 * is actually built on.
 */
export function stakePctForDay(day: number): number {
  return stakePctFor(MILLION_PLAN_RULES, day);
}

/** The odd the plan pencils in for a day. Day one is the only even-money one. */
export function plannedOddsForDay(day: number): number {
  return plannedOddsFor(MILLION_PLAN_RULES, day);
}

export function buildLadder(start = PLAN_START, days = PLAN_DAYS): PlanRung[] {
  return buildLadderFor({ ...MILLION_PLAN_RULES, days }, start);
}

/** The stake the plan calls for, as a share of what is actually in the bankroll. */
export function plannedStake(bankroll: number, day: number): number {
  return plannedStakeFor(MILLION_PLAN_RULES, bankroll, day);
}

export function rungForBankroll(bankroll: number, ladder = buildLadder()): number {
  return rungForBankrollIn(bankroll, ladder);
}

export function checkBet(input: BetCheckInput): PlanViolation[] {
  return checkBetAgainst(MILLION_PLAN_RULES, input);
}

export function chanceOfCompleting(fromDay: number, toDay = PLAN_DAYS): number {
  return chanceOfCompletingFor(MILLION_PLAN_RULES, fromDay, toDay);
}

export function costOfOneLoss(bankroll: number, day: number, ladder = buildLadder()) {
  return costOfOneLossFor(MILLION_PLAN_RULES, bankroll, day, ladder);
}

/** Expected number of days a run lasts before the first loss, at these odds. */
export function expectedDaysBeforeALoss(fromDay: number): number {
  const winChance = 1 / plannedOddsForDay(fromDay);
  if (winChance >= 1) return Infinity;
  return Number((1 / (1 - winChance)).toFixed(1));
}

export type { PlanSchedule, ScheduleState } from "@/lib/challengeSchedule";

/** Where today sits in the plan, over the document's 38 days by default. */
export function planSchedule(
  startDate: string | null,
  betsPlaced: number,
  days = PLAN_DAYS,
  today = new Date()
) {
  return schedule(startDate, betsPlaced, days, today);
}
