/**
 * The "Plano Milhão" as written: €10 turned into a million across 38 days,
 * one bet a day, each day's winnings staked again.
 *
 * The document's day-by-day table is not a list of arbitrary numbers, it is
 * generated by the rules beside it: a percentage of the bankroll that steps
 * down as the stake grows, at odds that cycle through a fixed set. Rebuilding
 * it from those rules rather than transcribing 38 rows means the ladder and
 * the rules can never drift apart, and the ladder still lands on the same
 * figures the brothers wrote down (day 38 ends just over €1,007,000).
 */

export const PLAN_START = 10;
export const PLAN_TARGET = 1_000_000;
export const PLAN_DAYS = 38;

/** The document's safe range for a single bet. */
export const ODDS_MIN = 1.75;
export const ODDS_MAX = 2.1;

/** Losses in a row after which the plan says to stop for the day. */
export const LOSS_STREAK_PAUSE = 3;

const ODDS_CYCLE = [1.85, 1.9, 1.95, 1.75, 1.8];

export interface PlanRung {
  day: number;
  stakePct: number;
  odds: number;
  bankrollStart: number;
  stake: number;
  profit: number;
  bankrollEnd: number;
}

function round(value: number, decimals = 2) {
  return Number(value.toFixed(decimals));
}

/**
 * What share of the bankroll the plan stakes on a given day.
 *
 * The written section of the document lists a different set of bands
 * (50/40/30/20) than its own table, and those bands do not reach a million —
 * they end around €14,000. These are the table's, which is the ladder the plan
 * is actually built on.
 */
export function stakePctForDay(day: number): number {
  if (day <= 15) return 0.5;
  if (day <= 29) return 0.4;
  return 0.3;
}

/** The odd the plan pencils in for a day. Day one is the only even-money one. */
export function plannedOddsForDay(day: number): number {
  if (day <= 1) return 2;
  return ODDS_CYCLE[(day - 2) % ODDS_CYCLE.length];
}

export function buildLadder(start = PLAN_START, days = PLAN_DAYS): PlanRung[] {
  const ladder: PlanRung[] = [];
  let bankroll = start;

  for (let day = 1; day <= days; day += 1) {
    const stakePct = stakePctForDay(day);
    const odds = plannedOddsForDay(day);
    const stake = round(bankroll * stakePct);
    const profit = round(stake * (odds - 1));
    const bankrollEnd = round(bankroll + profit);

    ladder.push({ day, stakePct, odds, bankrollStart: bankroll, stake, profit, bankrollEnd });
    bankroll = bankrollEnd;
  }

  return ladder;
}

/** The stake the plan calls for, as a share of what is actually in the bankroll. */
export function plannedStake(bankroll: number, day: number): number {
  if (bankroll <= 0) return 0;
  return round(bankroll * stakePctForDay(day));
}

/**
 * Which rung the bankroll has actually reached.
 *
 * This is deliberately not the same as the day count. Losing a day does not
 * send you back in time, it sends you back down the ladder, and the gap
 * between the two is the honest answer to "where are we?".
 */
export function rungForBankroll(bankroll: number, ladder = buildLadder()): number {
  if (bankroll < ladder[0].bankrollStart) return 0;
  let rung = 0;
  ladder.forEach((step) => {
    if (bankroll >= step.bankrollStart) rung = step.day;
  });
  return rung;
}

export type ViolationSeverity = "breach" | "note";

export interface PlanViolation {
  code: string;
  severity: ViolationSeverity;
  message: string;
}

export interface BetCheckInput {
  odds: number;
  stake: number;
  bankroll: number;
  day: number;
  betsPlacedToday: number;
  lossStreak: number;
}

/**
 * Everything about a proposed bet that the plan would object to.
 *
 * A breach is the plan being broken as written; a note is the plan being
 * followed cautiously. Both are shown, neither blocks the bet — the document
 * is a set of rules the two of them agreed to keep, not something the app gets
 * to enforce over their heads.
 */
export function checkBet({
  odds,
  stake,
  bankroll,
  day,
  betsPlacedToday,
  lossStreak,
}: BetCheckInput): PlanViolation[] {
  const violations: PlanViolation[] = [];
  const planned = plannedStake(bankroll, day);

  if (lossStreak >= LOSS_STREAK_PAUSE) {
    violations.push({
      code: "loss-streak",
      severity: "breach",
      message: `${lossStreak} perdas seguidas. O plano manda parar um dia e reavaliar antes da próxima aposta.`,
    });
  }

  if (betsPlacedToday > 0) {
    violations.push({
      code: "daily-limit",
      severity: "breach",
      message: "O plano é uma aposta por dia. Já há uma registada hoje.",
    });
  }

  if (odds > 0 && (odds < ODDS_MIN || odds > ODDS_MAX)) {
    violations.push({
      code: "odds-range",
      severity: "breach",
      message: `O plano só aceita odds entre ${ODDS_MIN.toFixed(2)} e ${ODDS_MAX.toFixed(
        2
      )}. Esta está a ${odds.toFixed(2)}.`,
    });
  }

  if (stake > planned + 0.01) {
    violations.push({
      code: "stake-over",
      severity: "breach",
      message: `Acima do plano: hoje são ${planned.toFixed(2)} € (${(
        stakePctForDay(day) * 100
      ).toFixed(0)}% da banca), não ${stake.toFixed(2)} €.`,
    });
  } else if (stake > 0 && stake < planned - 0.01) {
    violations.push({
      code: "stake-under",
      severity: "note",
      message: `Abaixo do plano: hoje seriam ${planned.toFixed(
        2
      )} €. Ficas mais atrás na escada, mas arriscas menos.`,
    });
  }

  return violations;
}

/**
 * The chance of the ladder actually being climbed to the end.
 *
 * Every rung needs the bet to land, so the whole plan is one long run of wins
 * and the odds multiply. This is the number a bankroll tool exists to show:
 * the table looks like a schedule, and it is really a parlay.
 */
export function chanceOfCompleting(fromDay: number, toDay = PLAN_DAYS): number {
  let chance = 1;
  for (let day = Math.max(1, fromDay); day <= toDay; day += 1) {
    chance *= 1 / plannedOddsForDay(day);
  }
  return chance;
}

/** How far down the ladder a single lost day puts you. */
export function costOfOneLoss(bankroll: number, day: number, ladder = buildLadder()) {
  const stake = plannedStake(bankroll, day);
  const after = round(Math.max(0, bankroll - stake));
  return {
    stake,
    bankrollAfter: after,
    rungBefore: rungForBankroll(bankroll, ladder),
    rungAfter: rungForBankroll(after, ladder),
  };
}

/** Expected number of days a run lasts before the first loss, at these odds. */
export function expectedDaysBeforeALoss(fromDay: number): number {
  const winChance = 1 / plannedOddsForDay(fromDay);
  if (winChance >= 1) return Infinity;
  return round(1 / (1 - winChance), 1);
}
